<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class QuanLyPhimSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('quan_ly_phims')->delete();
        DB::table('quan_ly_phims')->insert([
            [
                'ten_phim'         => 'Bộ tứ báo thủ',
                'slug_phim'        => 'bo-tu-bao-thu',
                'ngay_chieu'       => Carbon::parse('2025-01-29'),
                'thoi_luong'       => '133',
                'dao_dien'         => 'Trấn Thành',
                'hinh_anh'         => 'https://res.cloudinary.com/dfff9gqxw/image/upload/v1745075677/botubaothu_hdpm7g.jpg',
                'trailer_ytb'      => 'https://www.youtube.com/embed/zKMOgOWn8lQ?si=Z9vaeQU9zvxcSIHy',
                'dien_vien'        => 'Tran Thành, Le Duong Bao Lam, Le Giang, Uyen An, Quoc Anh, Tieu Vi, Ky Duyen',
                'nha_san_xuat'     => '3388 Films',
                'id_the_loai'      => '2',
                'gioi_han_do_tuoi' => '13+',
                'mo_ta'            => 'Bộ tứ báo thủ xoay quanh mối tình tay ba đầy trớ trêu nhưng cũng lắm chiêu trò giữa ba nhân vật chính.',
                'danh_gia'         => '9.5/10',
                'tinh_trang'       => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'ten_phim'         => 'Nụ hôn bạc tỷ',
                'slug_phim'        => 'nu-hon-bac-ty',
                'ngay_chieu'       => Carbon::parse('2025-01-29'),
                'thoi_luong'       => '100',
                'dao_dien'         => 'Thu Trang',
                'hinh_anh'         => 'https://res.cloudinary.com/dfff9gqxw/image/upload/v1745075897/nuhonbacti_vubymb.jpg',
                'trailer_ytb'      => 'https://www.youtube.com/embed/T6H8dxaoyI8?si=Z9vaeQU9zvxcSIHy',
                'dien_vien'        => 'Thu Trang, Đoàn Thiên Ân, Lê Xuân Tiền, Ma Ran Đô, Tiến Luật',
                'nha_san_xuat'     => 'Thu Trang',
                'id_the_loai'      => '2',
                'gioi_han_do_tuoi' => '16+',
                'mo_ta'            => 'Vân – cô gái bán bánh mì – vô tình gặp hai chàng trai trong một tai nạn, tạo nên mối tình tay ba đầy kịch tính và hài hước.',
                'danh_gia'         => '9.3/10',
                'tinh_trang'       => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'ten_phim'         => 'Yêu nhầm bạn thân',
                'slug_phim'        => 'yeu-nham-ban-than',
                'ngay_chieu'       => Carbon::parse('2025-01-29'),
                'thoi_luong'       => '106',
                'dao_dien'         => 'Nguyễn Quang Dũng, Diệp Thế Vinh',
                'hinh_anh'         => 'https://res.cloudinary.com/dfff9gqxw/image/upload/v1745076010/yeunhambanthan_oi4lzk.jpg',
                'trailer_ytb'      => 'https://www.youtube.com/embed/Z7AbUpnfcW8?si=GXcIQOuNXxq7XC-q',
                'dien_vien'        => 'Kaity Nguyễn, Trần Ngọc Vàng, Thanh Sơn',
                'nha_san_xuat'     => 'HK Film, Galaxy Studio',
                'id_the_loai'      => '2',
                'gioi_han_do_tuoi' => '16+',
                'mo_ta'            => 'Bình An – cô gái đang hạnh phúc với bạn trai – bỗng rơi vào tình thế “friend zone” với người bạn thân Toàn, tạo nên chuỗi tình huống dở khóc dở cười.',
                'danh_gia'         => '8.5/10',
                'tinh_trang'       => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'ten_phim'         => 'Gấu Yêu Của Anh',
                'slug_phim'        => 'gau-yeu-cua-anh',
                'ngay_chieu'       => Carbon::parse('2025-04-04'),
                'thoi_luong'       => '119',
                'dao_dien'         => 'Ping Lumpraploeng',
                'hinh_anh'         => 'https://res.cloudinary.com/dfff9gqxw/image/upload/v1745077515/470x700-muaythai_path0j.jpg',
                'trailer_ytb'      => 'https://www.youtube.com/embed/VQOOUxTah0w?si=SQ2DAWz5M6H4dwEz',
                'dien_vien'        => 'Jirayu La‑ongmani, Sananthachat Thanapatpisal, Chinawut Indracusin, Supathat Opas, Auttawut Inthong',
                'nha_san_xuat'     => '',
                'id_the_loai'      => '2',
                'gioi_han_do_tuoi' => '16+',
                'mo_ta'            => 'San mơ trở lại với sự nghiệp, bất ngờ “trượt chân” vào lưới tình với Momo, khiến bao tình huống dở khóc dở cười xảy ra.',
                'danh_gia'         => '7.8/10',
                'tinh_trang'       => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'ten_phim'         => 'Cưới Ma Giải Hạn',
                'slug_phim'        => 'cuoi-ma-giai-han',
                'ngay_chieu'       => Carbon::parse('2025-04-11'),
                'thoi_luong'       => '128',
                'dao_dien'         => 'Chayanop Bunprakob',
                'hinh_anh'         => 'https://res.cloudinary.com/dfff9gqxw/image/upload/v1745076369/cuumagiaihan_mcd5pi.jpg',
                'trailer_ytb'      => 'https://www.youtube.com/embed/a0XdUK9Onvc?si=KcpZeecpSCYNnL7m',
                'dien_vien'        => 'Putthipong Assaratanakul, Krit Amnuaydechkorn, Goy Arachaporn Pokinpakorn, Piyamas Monayakul, Jaturong Mokjok',
                'nha_san_xuat'     => 'Weerachai Yaikwawong, Banjong Pisanthanakun',
                'id_the_loai'      => '2',
                'gioi_han_do_tuoi' => '18+',
                'mo_ta'            => 'Menn – chàng trai thẳng – bỗng bị ràng buộc bởi phong tục minh hôn với hồn ma, tạo nên phiêu lưu vừa lầy lội vừa cảm động.',
                'danh_gia'         => '8.5/10',
                'tinh_trang'       => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'ten_phim'         => 'Siêu Nhân Nhí Đại Náo Rừng Xanh',
                'slug_phim'        => 'sieu-nhan-nhi-dai-nao-rung-xanh',
                'ngay_chieu'       => Carbon::parse('2025-04-11'),
                'thoi_luong'       => '82',
                'dao_dien'         => 'Behnoud Nekooei',
                'hinh_anh'         => 'https://res.cloudinary.com/dfff9gqxw/image/upload/v1745076868/sieunhannhi_b5ggkn.jpg',
                'trailer_ytb'      => 'https://www.youtube.com/embed/sdV_dQiyG1s?si=tULeRwvNkGRihq9a"',
                'dien_vien'        => 'Hooman Hajabdollahi, Javad Pezeshkian, Hedayat Hashemi, Mir Taher Mazloomi, Tooraj Nasr',
                'nha_san_xuat'     => 'Hamed Jafari',
                'id_the_loai'      => '3',
                'gioi_han_do_tuoi' => '13+',
                'mo_ta'            => 'Cậu bé mơ làm siêu anh hùng bỗng bước vào cuộc phiêu lưu giải cứu chú hổ trước nhóm thợ săn dữ tợn.',
                'danh_gia'         => '6.6/10',
                'tinh_trang'       => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'ten_phim'         => 'Một Bộ Phim Minecraft',
                'slug_phim'        => 'mot-bo-phim-minecraft',
                'ngay_chieu'       => Carbon::parse('2025-04-04'),
                'thoi_luong'       => '101',
                'dao_dien'         => 'Jared Hess',
                'hinh_anh'         => 'https://res.cloudinary.com/dfff9gqxw/image/upload/v1745077134/minecraft_kftqsr.jpg',
                'trailer_ytb'      => 'https://www.youtube.com/embed/O1f6L1Pqu28?si=FeCMKaUuNSwC26X9',
                'dien_vien'        => 'Jason Momoa, Jack Black, Emma Myers, Sebastian Eugene Hansen, Danielle Brooks',
                'nha_san_xuat'     => 'Roy Lee, Jill Messick',
                'id_the_loai'      => '4',
                'gioi_han_do_tuoi' => '13+',
                'mo_ta'            => 'Bốn người bị kéo vào thế giới Minecraft, phải học cách sinh tồn và trở về nhà qua hành trình đầy khối lập phương kỳ ảo.',
                'danh_gia'         => '8.7/10',
                'tinh_trang'       => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'ten_phim'         => 'Pororo: Thám Hiểm Đại Dương Xanh',
                'slug_phim'        => 'pororo-tham-hiem-dai-duong-xanh',
                'ngay_chieu'       => Carbon::parse('2025-04-04'),
                'thoi_luong'       => '71',
                'dao_dien'         => 'Yoon Je-wan',
                'hinh_anh'         => 'https://res.cloudinary.com/dfff9gqxw/image/upload/v1745077334/thamhiemdaiduowng_rlsl4h.jpg',
                'trailer_ytb'      => 'https://www.youtube.com/embed/rTsV2tzDv6Y?si=1FoIFcIPMDOjjNTe',
                'dien_vien'        => 'Lee Sun, Lee Mi-ja, Ham Su-jung, Hong So-young, Jung Mi-sook',
                'nha_san_xuat'     => 'Kim Hyun-ho, Park Hyun-kuk',
                'id_the_loai'      => '4',
                'gioi_han_do_tuoi' => '13+',
                'mo_ta'            => 'Pororo và bạn bè khám phá đại dương, đối mặt quái vật Seatus và học bài học về biển cả.',
                'danh_gia'         => '8.5/10',
                'tinh_trang'       => 1,
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'ten_phim' => 'JUNG KOOK: I AM STILL',
                'slug_phim' => 'jung-kook-i-am-still',
                'ngay_chieu' => Carbon::parse('2024-01-01'),
                'thoi_luong' => '120',
                'dao_dien' => 'Đạo Diễn 1',
                'hinh_anh' => 'https://media.lottecinemavn.com/Media/MovieFile/MovieImg/202409/11559_103_100001.jpg',
                'trailer_ytb' => 'https://www.youtube.com/embed/LWkh_hXeEeg?si=eUd_mxvnOCXi9T-G',
                'dien_vien' => 'Diễn Viên 1, Diễn Viên 2',
                'nha_san_xuat' => 'Nhà Sản Xuất 1',
                'id_the_loai' => '1',
                'gioi_han_do_tuoi' => '18+',
                'mo_ta' => 'Mô tả phim 1',
                'danh_gia' => '8/10',
                'tinh_trang' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Thêm 14 bản ghi khác với các giá trị tương ứng
            [
                'ten_phim' => 'TEE YOD: QUỶ ĂN TẠNG PHẦN 2',
                'slug_phim' => 'tee-yod-quy-an-tang-phan-2',
                'ngay_chieu' => Carbon::parse('2024-02-01'),
                'thoi_luong' => '90',
                'dao_dien' => 'Đạo Diễn 2',
                'hinh_anh' => 'https://media.lottecinemavn.com/Media/MovieFile/MovieImg/202410/11567_103_100006.jpg',
                'trailer_ytb' => 'https://www.youtube.com/embed/wJO_vIDZn-I?si=uFRXvxKDYh9bxLmw',
                'dien_vien' => 'Diễn Viên 3, Diễn Viên 4',
                'nha_san_xuat' => 'Nhà Sản Xuất 2',
                'id_the_loai' => '2',
                'gioi_han_do_tuoi' => '16+',
                'mo_ta' => 'Mô tả phim 2',
                'danh_gia' => '4/5',
                'tinh_trang' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // ... tiếp tục thêm các bản ghi khác
            [
                'ten_phim' => 'ROBOT HOANG DÃ',
                'slug_phim' => 'robot-hoang-da',
                'ngay_chieu' => Carbon::parse('2024-03-01'),
                'thoi_luong' => '110',
                'dao_dien' => 'Đạo Diễn 3',
                'hinh_anh' => 'https://media.lottecinemavn.com/Media/MovieFile/MovieImg/202410/11482_103_100002.jpg',
                'trailer_ytb' => 'https://www.youtube.com/embed/QT5j0Uf-rdM?si=UbvG5a-dbKxNS_E_',
                'dien_vien' => 'Diễn Viên 5, Diễn Viên 6',
                'nha_san_xuat' => 'Nhà Sản Xuất 3',
                'id_the_loai' => '3',
                'gioi_han_do_tuoi' => '13+',
                'mo_ta' => 'Mô tả phim 3',
                'danh_gia' => '3/5',
                'tinh_trang' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Lặp lại cho đến khi đủ 15 bản ghi
            [
                'ten_phim' => 'CÁM',
                'slug_phim' => 'cam',
                'ngay_chieu' => Carbon::parse('2024-03-01'),
                'thoi_luong' => '110',
                'dao_dien' => 'Đạo Diễn 3',
                'hinh_anh' => 'https://media.lottecinemavn.com/Media/MovieFile/MovieImg/202409/11507_103_100004.jpg',
                'trailer_ytb' => 'https://www.youtube.com/embed/rbHUhCcSXEM?si=gb0k7EDOzombG-1V',
                'dien_vien' => 'Diễn Viên 5, Diễn Viên 6',
                'nha_san_xuat' => 'Nhà Sản Xuất 3',
                'id_the_loai' => '3',
                'gioi_han_do_tuoi' => '13+',
                'mo_ta' => 'Mô tả phim 3',
                'danh_gia' => '3/5',
                'tinh_trang' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Lặp lại cho đến khi đủ 15 bản ghi
            [
                'ten_phim' => 'FUBAO: BẢO BỐI CỦA ÔNG',
                'slug_phim' => 'fubao-bao-boi-cua-ong',
                'ngay_chieu' => Carbon::parse('2024-03-01'),
                'thoi_luong' => '110',
                'dao_dien' => 'Đạo Diễn 3',
                'hinh_anh' => 'https://media.lottecinemavn.com/Media/MovieFile/MovieImg/202410/11574_103_100002.jpg',
                'trailer_ytb' => 'https://www.youtube.com/embed/erxeLAg85fg?si=txZXIotsKCYep884',
                'dien_vien' => 'Diễn Viên 5, Diễn Viên 6',
                'nha_san_xuat' => 'Nhà Sản Xuất 3',
                'id_the_loai' => '3',
                'gioi_han_do_tuoi' => '13+',
                'mo_ta' => 'Mô tả phim 3',
                'danh_gia' => '3/5',
                'tinh_trang' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Lặp lại cho đến khi đủ 15 bản ghi
            [
                'ten_phim' => 'BIỆT ĐỘI HOT GIRL',
                'slug_phim' => 'biet-doi-hot-girl',
                'ngay_chieu' => Carbon::parse('2024-03-01'),
                'thoi_luong' => '110',
                'dao_dien' => 'Đạo Diễn 3',
                'hinh_anh' => 'https://media.lottecinemavn.com/Media/MovieFile/MovieImg/202410/11595_103_100001.jpg',
                'trailer_ytb' => 'https://www.youtube.com/embed/SjkcA2ZCmDU?si=LZGI2Hh0R3W3v_xq',
                'dien_vien' => 'Diễn Viên 5, Diễn Viên 6',
                'nha_san_xuat' => 'Nhà Sản Xuất 3',
                'id_the_loai' => '3',
                'gioi_han_do_tuoi' => '13+',
                'mo_ta' => 'Mô tả phim 3',
                'danh_gia' => '3/5',
                'tinh_trang' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Lặp lại cho đến khi đủ 15 bản ghi
            [
                'ten_phim' => 'TRÒ CHƠI NHÂN TÍNH',
                'slug_phim' => 'tro-choi-nhan-tinh',
                'ngay_chieu' => Carbon::parse('2024-03-01'),
                'thoi_luong' => '110',
                'dao_dien' => 'Đạo Diễn 3',
                'hinh_anh' => 'https://media.lottecinemavn.com/Media/MovieFile/MovieImg/202410/11592_103_100001.jpg',
                'trailer_ytb' => 'https://www.youtube.com/embed/h0_kFeF__rc?si=0fZ44RWSmCS4yy-O',
                'dien_vien' => 'Diễn Viên 5, Diễn Viên 6',
                'nha_san_xuat' => 'Nhà Sản Xuất 3',
                'id_the_loai' => '3',
                'gioi_han_do_tuoi' => '13+',
                'mo_ta' => 'Mô tả phim 3',
                'danh_gia' => '3/5',
                'tinh_trang' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ten_phim' => 'CÔ DÂU HÀO MÔN',
                'slug_phim' => 'co-dau-hao-mon',
                'ngay_chieu' => Carbon::parse('2024-03-01'),
                'thoi_luong' => '110',
                'dao_dien' => 'Đạo Diễn 3',
                'hinh_anh' => 'https://media.lottecinemavn.com/Media/MovieFile/MovieImg/202410/11556_103_100002.jpg',
                'trailer_ytb' => 'https://www.youtube.com/embed/IILf3ZEBnmM?si=oa9jD-RWhyleliWG',
                'dien_vien' => 'Diễn Viên 5, Diễn Viên 6',
                'nha_san_xuat' => 'Nhà Sản Xuất 3',
                'id_the_loai' => '3',
                'gioi_han_do_tuoi' => '13+',
                'mo_ta' => 'Mô tả phim 3',
                'danh_gia' => '3/5',
                'tinh_trang' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

        ]);
    }
}
